apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: dify
type: Opaque
data:
  REDIS_MASTER_PASSWORD: ZGlmeWFpMTIzNDU2
  REDIS_MASTER_USERNAME: ZGV2ZWxvcGVy
  REDIS_PASSWORD: ZGlmeWFpMTIzNDU2
