apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: dify
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          command: ["redis-server", "/data/redis.conf"]
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 30
            timeoutSeconds: 4
          volumeMounts:
            - name: config-volume
              mountPath: /data
          env:
            - name: REDIS_MASTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_MASTER_PASSWORD
            - name: REDIS_MASTER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_MASTER_USERNAME
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
      initContainers:
        - name: config-substitute
          image: alpine:3.12
          command:
            [
              "sh",
              "-c",
              "apk add --no-cache gettext && envsubst < /config/redis.conf > /data/redis.conf",
            ]
          env:
            - name: REDIS_MASTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_MASTER_PASSWORD
            - name: REDIS_MASTER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_MASTER_USERNAME
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
          volumeMounts:
            - name: config-volume
              mountPath: /data
            - name: config-template
              mountPath: /config
      volumes:
        - name: config-volume
          emptyDir: {}
        - name: config-template
          configMap:
            name: redis-config
            items:
              - key: redis.conf
                path: redis.conf
