apiVersion: apps/v1
kind: Deployment
metadata:
  name: dify-worker
  namespace: dify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dify-worker
  template:
    metadata:
      labels:
        app: dify-worker
    spec:
      restartPolicy: Always
      containers:
        - name: dify-worker
          image: langgenius/dify-worker:0.6.15
          ports:
            - name: http
              containerPort: 5001
              protocol: TCP
          env:
            MODE: worker
            LOG_LEVEL: INFO
            DEBUG: false
            FLASK_DEBUG: false
            SECRET_KEY: sk-9f73s3ljTXVcMT3Blb3ljTqtsKiGHXVcMT3BlbkFJLK7U
            CONSOLE_WEB_URL: http://dify-web.dify.svc.cluster.local:3000
            CONSOLE_API_URL: http://dify-worker.dify.svc.cluster.local:5001
            SERVICE_API_URL: http://dify-worker.dify.svc.cluster.local:5001
            APP_WEB_URL: http://dify-web.dify.svc.cluster.local:3000
            CHECK_UPDATE_URL: https://updates.dify.ai
            OPENAI_API_BASE: https://api.openai.com/v1
            FILES_ACCESS_TIMEOUT: 300
            APP_MAX_ACTIVE_REQUESTS: 0
            MIGRATION_ENABLED: true
            DEPLOY_ENV: PRODUCTION
            DIFY_BIND_ADDRESS: 0.0.0.0
            DIFY_PORT: 5001
            GUNICORN_TIMEOUT: 360
            API_TOOL_DEFAULT_CONNECT_TIMEOUT: 10
            API_TOOL_DEFAULT_READ_TIMEOUT: 60
            DB_USERNAME: postgres
            DB_PASSWORD: difyai123456
            DB_HOST: postgres.diffy.svc.cluster.local
            DB_PORT: 5432
            DB_DATABASE: dify-db
            SQLALCHEMY_POOL_SIZE: 30
            SQLALCHEMY_POOL_RECYCLE: 3600
            SQLALCHEMY_ECHO: false
            REDIS_HOST: redis.dify.svc.cluster.local
            REDIS_PORT: 6379
            REDIS_USERNAME: developer
            REDIS_PASSWORD: difyai123456
            REDIS_USE_SSL: false
            REDIS_DB: 0
            CELERY_BROKER_URL: redis://developer:difyai123456@redis.dify.svc.cluster.local:6379/1
            BROKER_USE_SSL: false
            WEB_API_CORS_ALLOW_ORIGINS: "*"
            CONSOLE_CORS_ALLOW_ORIGINS: "*"
            STORAGE_TYPE: local
            STORAGE_LOCAL_PATH: storage
            VECTOR_STORE: weaviate
            WEAVIATE_ENDPOINT: http://weaviate.dify.svc.cluster.local:8080
            WEAVIATE_API_KEY: WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih
            UPLOAD_FILE_SIZE_LIMIT: 15
            UPLOAD_FILE_BATCH_LIMIT: 5
            ETL_TYPE: dify
            MULTIMODAL_SEND_IMAGE_FORMAT: base64
            UPLOAD_IMAGE_FILE_SIZE_LIMIT: 10
            INDEXING_MAX_SEGMENTATION_TOKENS_LENGTH: 1000
            INVITE_EXPIRY_HOURS: 72
            RESET_PASSWORD_TOKEN_EXPIRY_HOURS: 24
            CODE_EXECUTION_ENDPOINT: http://sandbox.dify.svc.cluster.local:8194
            CODE_EXECUTION_API_KEY: dify-sandbox
            CODE_MAX_NUMBER: 9223372036854775807
            CODE_MIN_NUMBER: -9223372036854775808
            CODE_MAX_STRING_LENGTH: 80000
            TEMPLATE_TRANSFORM_MAX_LENGTH: 80000
            CODE_MAX_STRING_ARRAY_LENGTH: 30
            CODE_MAX_OBJECT_ARRAY_LENGTH: 30
            CODE_MAX_NUMBER_ARRAY_LENGTH: 1000
            SSRF_PROXY_HTTP_URL: http://ssrf-proxy.dify.svc.cluster.local:3128
            SSRF_PROXY_HTTPS_URL: http://ssrf-proxy.dify.svc.cluster.local:3128
